#Launch the PowerShell Console
#Run PowerShell as admin
Set-ExecutionPolicy -ExecutionPolicy AllSigned
Install-Module -Name Az.Security -Force

# Onboard Security Center using PowerShell
#Register your subscriptions to the Security Center Resource Provider:
Set-AzContext -Subscription "Subscription ID"
Register-AzResourceProvider -ProviderNamespace 'Microsoft.Security'

#Set the coverage level (pricing tier) of the subscriptions (If not defined, the pricing tier is set to Free):
Set-AzContext -Subscription " Subscription ID "
Set-AzSecurityPricing -Name "default" -PricingTier "Standard"	


#Configure a Log Analytics workspace to which the agents will report. You must have a Log Analytics workspace that you already created, that the subscription’s VMs will report to
Set-AzSecurityWorkspaceSetting -Name "default" -Scope
"/subscriptions/ Subscription ID " -WorkspaceId"/subscriptions/ Subscription ID /resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace"

#Auto-provision installation of the Microsoft Monitoring Agent on your Azure VMs:
Set-AzContext -Subscription " Subscription ID "

Set-AzSecurityAutoProvisioningSetting -Name "default" -EnableAutoProvision

#It is highly recommended that customer define the security contact details for the subscriptions onboarded, which will be used as the recipients of alerts and notifications generated by Security Center
Set-AzSecurityContact -Name "default1" -Email "CISO@my-org.com" -Phone "214275XXXX" -AlertAdmin -NotifyOnAlert

#Assign the default Security Center policy initiative:
Register-AzResourceProvider -ProviderNamespace 'Microsoft.PolicyInsights'
$Policy = Get-AzPolicySetDefinition | where {$_.Properties.displayName -EQ '[Preview]: Enable Monitoring in Azure Security Center'}
New-AzPolicyAssignment -Name 'ASC Default Subscription ID ' -DisplayName 'Security Center Default <subscription ID>' -PolicySetDefinition $Policy -Scope '/subscriptions/ Subscription ID '
