ARM_CLIENT_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
ARM_CLIENT_SECRET=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
ARM_SUBSCRIPTION_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
ARM_TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
ARM_OBJECT_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx